server:
  port: 8888
spring:
  application:
    name: running-info-analysis-service
  datasource:
    url: jdbc:mysql://localhost:3306/running_info_analysis_db
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
